# Generated by Django 2.0.2 on 2018-02-07 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180206_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='gender',
        ),
    ]
