# Generated by Django 2.0.2 on 2018-02-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180208_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_image',
            field=models.ImageField(upload_to='base/static/images/', verbose_name='Зображення'),
        ),
    ]
