# Generated by Django 2.0.2 on 2018-02-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20180208_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('M', 'Хлопець'), ('F', 'Дівчина')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Назва'),
        ),
    ]
