# Generated by Django 2.0.2 on 2018-03-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20180212_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='friday_time',
            field=models.CharField(default='00:00', max_length=100, verbose_name="П'ятниця"),
        ),
        migrations.AddField(
            model_name='group',
            name='monday_time',
            field=models.CharField(default='00:00', max_length=100, verbose_name='Понеділок'),
        ),
        migrations.AddField(
            model_name='group',
            name='saturday_time',
            field=models.CharField(default='00:00', max_length=100, verbose_name='Субота'),
        ),
        migrations.AddField(
            model_name='group',
            name='sunday_time',
            field=models.CharField(default='00:00', max_length=100, verbose_name='Неділя'),
        ),
        migrations.AddField(
            model_name='group',
            name='thursday_time',
            field=models.CharField(default='00:00', max_length=100, verbose_name='Четвер'),
        ),
        migrations.AddField(
            model_name='group',
            name='tuesday_time',
            field=models.CharField(default='00:00', max_length=100, verbose_name='Вівторок'),
        ),
        migrations.AddField(
            model_name='group',
            name='wednesday_time',
            field=models.CharField(default='00:00', max_length=100, verbose_name='Середа'),
        ),
    ]
