# Generated by Django 2.0.2 on 2018-03-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20180319_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='friday_time',
            field=models.CharField(default='-', max_length=100, verbose_name="П'ятниця"),
        ),
        migrations.AlterField(
            model_name='group',
            name='monday_time',
            field=models.CharField(default='-', max_length=100, verbose_name='Понеділок'),
        ),
        migrations.AlterField(
            model_name='group',
            name='saturday_time',
            field=models.CharField(default='-', max_length=100, verbose_name='Субота'),
        ),
        migrations.AlterField(
            model_name='group',
            name='sunday_time',
            field=models.CharField(default='-', max_length=100, verbose_name='Неділя'),
        ),
        migrations.AlterField(
            model_name='group',
            name='thursday_time',
            field=models.CharField(default='-', max_length=100, verbose_name='Четвер'),
        ),
        migrations.AlterField(
            model_name='group',
            name='tuesday_time',
            field=models.CharField(default='-', max_length=100, verbose_name='Вівторок'),
        ),
        migrations.AlterField(
            model_name='group',
            name='wednesday_time',
            field=models.CharField(default='-', max_length=100, verbose_name='Середа'),
        ),
    ]
