# Generated by Django 2.0.2 on 2018-03-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20180319_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesForSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='base/static/images/')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='images_for_slider',
            field=models.ManyToManyField(related_name='children', to='base.ImagesForSlider'),
        ),
    ]
