# Generated by Django 2.0.2 on 2018-04-16 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20180320_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='images_for_slider',
        ),
    ]
