# Generated by Django 2.0.2 on 2018-04-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20180416_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='images_for_slider',
            field=models.ManyToManyField(related_name='group', to='base.ImagesForSlider'),
        ),
    ]
