# Generated by Django 2.0.2 on 2018-04-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_imagesforslider_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesforslider',
            name='image',
            field=models.ImageField(upload_to='base/static/images/', verbose_name='Зображення'),
        ),
    ]
