# Generated by Django 2.0.2 on 2018-04-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20180416_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.FileField(upload_to='base/static/music/', verbose_name='Музика')),
                ('music_name', models.CharField(default='Music', max_length=100, unique=True, verbose_name='Назва')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='music_for_player',
            field=models.ManyToManyField(related_name='group', to='base.GroupMusic'),
        ),
    ]
